Feat: Удаление фильмов и пользователей
Deathriot/java-filmorate-group-project pull request #1
Opened 2024-04-03 22:12 UTC by MayFoxes

Добавления:
  1) Тесты для удаления пользователя и фильма;
  2) Добавлена проверка наличия имени пользователя;
  3) В schema.sql в таблице "Users" строки: логин и мейл теперь уникальны.

Исправления в основном коде:
  1) Исправлен pom.xml мешающий локально проходить тесты postman;
  2) Исправлены интеграционные тесты;
  3) Незначительные стилистические изменения.

2024-04-06 08:45 UTC, vladbakushkin requested changes
Привет, оставил небольшое замечание, которое нужно поправить. В остальном все хорошо.

2024-04-06 08:45 UTC, vladbakushkin commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/dao/UserDbStorage.java
> +        }
На самом деле достаточно одной проверки `.isBlank()`, так как она включает проверку на null, на пустую строку и на строку, состоящую из пробельных символов

https://www.baeldung.com/java-string-isempty-vs-isblank

https://ru.stackoverflow.com/questions/712136/%D0%92-%D1%87%D1%91%D0%BC-%D0%BE%D1%82%D0%BB%D0%B8%D1%87%D0%B8%D0%B5-isblank-vs-isempty

2024-04-06 08:45 UTC, vladbakushkin commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/dao/UserDbStorage.java
> +        }
И еще эта проверка дублируется со строкой 36

2024-04-06 10:51 UTC, MayFoxes commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/dao/UserDbStorage.java
> +        }
Похоже на меня, создать метод, чтобы реализовать его отдельно. Исправил, оставил метод checkUserName, убрал его реализацию в addUser

2024-04-06 18:25 UTC, SmirnovSA1 approved these changes
В остальном отлично. После исправлений замечаний и пуша в ветку можно закрывать

2024-04-06 18:25 UTC, SmirnovSA1 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/dao/UserDbStorage.java
> +        if (user.getName() == null || user.getName().isEmpty() || user.getName().isBlank()) {
А зачем второй раз проверку делать, если выше ты уже вызвал checkUserName?

2024-04-06 18:25 UTC, SmirnovSA1 commented on src/main/resources/schema.sql
> +    EMAIL    VARCHAR(255) NOT NULL UNIQUE,
Думаю, что можно добавить еще проверку CHECK (user_email <> ''), чтобы не допустить добавления в таблицу пустых значений

2024-04-06 18:25 UTC, SmirnovSA1 commented on src/main/resources/schema.sql
> +    LOGIN    VARCHAR(50) NOT NULL UNIQUE,
Также можно добавить еще проверку CHECK (user_login <> ''), чтобы не допустить добавления в таблицу пустых значений

2024-04-07 15:45 UTC, vladbakushkin approved these changes

2024-04-07 15:49 UTC, SmirnovSA1 commented on src/main/resources/schema.sql
> +    EMAIL    VARCHAR(255) CHECK (user_email <> '') NOT NULL UNIQUE,
Убери префикс у поля. Вместо user_email нужно оставить email
В таблице же поле называется EMAIL))

2024-04-07 15:50 UTC, SmirnovSA1 commented on src/main/resources/schema.sql
> +    LOGIN    VARCHAR(50) CHECK (user_login <> '') NOT NULL UNIQUE,
Тут тоже самое - убери префикс у поля. Вместо user_login нужно оставить login.

2024-04-07 17:23 UTC, merged