Добавление режиссёров в фильмы. add-director
Deathriot/java-filmorate-group-project pull request #4
Opened 2024-04-05 12:03 UTC by kosovmaster

Добавлены классы:
1. controller - DirectorController
2. model - Director
3. service - DirectorService и DirectorServiceImpl
4. storage - DirectorStorage и DirectorDbStorage
5. validator - DateValidator и IsAfterDate

Добавлен основной функционал:
1. Создание режиссёра
2. Получение режиссёра по id
3. Вывод списка всех режиссёров
4. Изменение режиссёра
5. Удаление режиссёра

Дополнительный функционал:
1. Добавлена аннотация @IsAfterDate, которая решает часть проблем с тестами, связанными с датой.
2. Добавлены таблицы DIRECTOR и FILM_DIRECTOR в schema.sql, а также немного изменен порядок создания таблиц.
3. Добавлены pom зависимости

2024-04-07 21:57 UTC, vladbakushkin requested changes
Оставил несколько замечаний, которые неплохо бы поправить, а в остальном все отлично.

2024-04-07 21:57 UTC, vladbakushkin commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService/DirectorServiceImpl.java
> +    }
Можно добавить аннотацию ломбока `@RequiredArgsConstructor` и убрать конструктор для унификации с остальным кодом

2024-04-07 21:57 UTC, vladbakushkin commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/dao/DirectorDbStorage.java
> +    }
Аналогично предыдущему комментарию

2024-04-07 21:57 UTC, vladbakushkin commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmDbStorageTest.java
Этого файла быть не должно, надо посмотреть, почему он остался после rebase.

2024-04-07 21:57 UTC, vladbakushkin commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/dao/DirectorDbStorage.java
> +        return director;
Лучше возвращать объект из БД, например, через метод `getDirectorById()`, чтобы убедиться, что режиссер успешно сохранился в БД. Сейчас возвращается тот же объект, что пришел на вход контроллера, но с новым id.

2024-04-07 21:57 UTC, vladbakushkin commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/dao/DirectorDbStorage.java
> +    }
Аналогично созданию, лучше возвращать обновленного режиссера из БД.

2024-04-07 21:57 UTC, vladbakushkin commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/dao/DirectorDbStorage.java
> +    }
Тут больше подойдет NotFoundException

2024-04-07 21:57 UTC, vladbakushkin commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/dao/DirectorDbStorage.java
> +    }
Круто, что применил NamedParameterJdbcTemplate

2024-04-07 21:57 UTC, vladbakushkin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    }
Что-то этот метод не очень органично смотрится в классе Film. Может перенесем его в storage?

2024-04-08 16:25 UTC, MayFoxes commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    public DirectorController(DirectorService directorService) {
Можно использовать аннотацию @AllArgsConstructor или @RequiredArgsConstructor

2024-04-08 16:25 UTC, MayFoxes commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@RequiredArgsConstructor
Если решил поменять аннотацию конструктора, то тогда надо ее во всех контроллерах поменять, чтобы было единообразие кода.

2024-04-08 16:25 UTC, MayFoxes commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    protected Mpa mpa;
Почему protected ?

2024-04-08 16:25 UTC, MayFoxes commented on src/main/java/ru/yandex/practicum/filmorate/service/director/DirectorService.java
> +    Director getDirectorById(int id);
Возможно стоит поменять int на Integer

2024-04-08 16:25 UTC, MayFoxes commented on src/main/java/ru/yandex/practicum/filmorate/service/director/DirectorService.java
> +    void deleteDirectorById(int id);
Аналогично вышесказанному

2024-04-08 16:55 UTC, vladbakushkin approved these changes

2024-04-08 18:38 UTC, MayFoxes approved these changes

2024-04-08 18:43 UTC, merged